Resources:
  OdfProcessorServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: ${self:custom.stackResourcePrefix}-role
      PermissionsBoundary: ${self:custom.permissionsBoundary}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: ${self:custom.stackResourcePrefix}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sqs:ChangeMessageVisibility
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                Resource: ${self:custom.requestIntakeQueue}
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: '*'        
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                Resource: '*'
        - PolicyName: ${self:custom.stackResourcePrefix}-s3-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: arn:aws:s3:::${self:custom.resourceNamePrefix}-main-file-feed-artifact-bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: arn:aws:s3:::${self:custom.resourceNamePrefix}-main-file-feed-artifact-bucket/*